### ISSUE TITLE
Unable to cast object of type 'System.nint' to type 'System.Int32'

### ISSUE THREAD

**Issue by PelleRavn** [aritchie/settings#1]
So, I'm using the new updated version of Acr.Settings, and is now running into an typecast issue.

I'm setting an int using the generic:
``` _settings.Set<int>("Version", _currentVersion); ```

This works find, no issue there. But when I select it out again, still using a generic:
``` _settings.Get<int>("Version"); ```

it crashes with an typecast error:
*Unable to cast object of type 'System.nint' to type 'System.Int32'*

I looked at the source, and is guessing the error lies in **Acr.Settings.iOS/SettingsImpl.cs**, line 58-59:
``` 
case TypeCode.Int32: 
   return this.prefs.IntForKey(key); 
```

The NSUserDefaults will return a native type (nint) and not an int, as I would expect, when I'm using it in my core project. A simple typecast to int after return (*return (int)this.prefs.IntForKey(key);*) should do the trick - But not completely sure, haven't tried.
The solution for now, have been to change the generic to string, and then typecast it using Int32.Parse(), really not a good solution, but it works.

(Maybe some unit tests would be good to avoid thise kind of issues?)

**Comment by aritchie** [comment]
Actually, I do have unit tests (around this exact test case too) and they were passing a couple of weeks ago with the last release.

This looks as though xamarin has changed something in their code seeing as IntForKey returns nint, but FloatForKey returns float instead of nfloat.

**Comment by PelleRavn** [comment]
Shouldn't you just typecast the float then, instead of a warning and the possibility that it breaks in the future (it would make sense that NSUserDefaults returns a native type in both cases) - The typecast would prevent that case. I know this will make your unit test less usable, but I think I would prefer the chance of no crashes :)

**Comment by aritchie** [comment]
I'm not inserting the other cast because I want it for tracking purposes at the moment
