### ISSUE TITLE
FileCreationMode.WorldWriteable seems unsupported (not just deprecated) by now

### ISSUE THREAD

**Issue by adrianliechti** [aritchie/settings#12]
we noticed problems reading settings on Android 7.x when compiling against API Level 24.
 ---> Java.Lang.RuntimeException: MODE_WORLD_WRITEABLE no longer supported

The flag is used on reading preferences with a namespace

return this.nameSpace == null
                ? PreferenceManager.GetDefaultSharedPreferences(ctx)
                : ctx.GetSharedPreferences(this.nameSpace, FileCreationMode.WorldWriteable);

see also:
https://developer.android.com/reference/android/content/Context.html#MODE_WORLD_WRITEABLE

thanks having a look on that
cheer, adrian

**Comment by aritchie** [comment]
It means I'll likely have to drop this as a feature
