### ISSUE TITLE
Platform plugin not found

### ISSUE THREAD

**Issue by GingerMcMurray** [aritchie/settings#13]
I'm pretty sure this is a configuration issue on my end but I haven't been able to find a solution. When I include Acr.Settings and its dependencies and then add the folowing line:

var int1 = Settings.Local.Get<int>("Key");

I get the following error:

Settings.Local	System.ArgumentException: Platform plugin not found.  Did you reference the nuget package in your platform project?	

Any help would be greatly appreciated.

**Comment by aritchie** [comment]
Install the Nuget package into your main iOS and android projects

**Comment by GingerMcMurray** [comment]
I did that already. I was able to get Xam.Plugin.Settings working and don't need the extra features this plugin brings, so I'm good. If I ever need to upgrade you may hear from me again. ;-)

Thanks!
Ginger
