### ISSUE TITLE
Exception on Android when resuming from sleep 

### ISSUE THREAD

**Issue by MisterJimson** [aritchie/settings#14]
When my app resumes from sleep and tried to access a setting sometimes I get the following exception.

```
System.InvalidOperationException Trying to dispose handle of type 'Invalid' which is not supported.
Java.Lang.Object.Dispose(object instance, ref IntPtr handle, IntPtr key_handle, JObjectRefType handle_type)<dce3153a3aff4eedadb33afa199056cc>:0
Java.Lang.Object.Dispose()<dce3153a3aff4eedadb33afa199056cc>:0
Acr.Settings.SettingsImpl.Contains(string key)<a2592a0fc5db4cb488c609322d740142>:0
Acr.Settings.AbstractSettings.Get<T>(string key, T defaultValue)<94b6c4820a8c47048016130b6d3f7f62>:0
```

**Comment by aritchie** [comment]
Is there anymore to the stacktrace?   I just want to know why the app context is null.

It has something to do with this
            var ctx = Application.Context.ApplicationContext;
            return this.nameSpace == null
                ? PreferenceManager.GetDefaultSharedPreferences(ctx)

**Comment by MisterJimson** [comment]
The only other thing I have is that the exception I get from the library itself is

`System.ArgumentExceptionError getting key: (key name)`

The InvalidOperationException is the inner exception.

This is all I have.

**Comment by aritchie** [comment]
6.0 has some things that could fix this, though I have not been able to reproduce.
