### ISSUE TITLE
Xamarin.Mac - Issue with `System.ComponentModel.INotifyPropertyChanged'

### ISSUE THREAD

**Issue by Dids** [aritchie/settings#17]
Even though it's not really mentioned anywhere, I noticed that this library works nicely with Xamarin.Mac.

I'm now trying to use `Bind()` (ie. `_settings.Bind<MyModel>();`, `MyModel` being a subclass of a base class, which implements INotifyPropertyChanged), but running into dependency/reference issues for some reason.

Here's what it throws when compiling (only when I try to use `Bind()`:
```
Error CS0012: The type `System.ComponentModel.INotifyPropertyChanged' is defined in an assembly that is not referenced. Consider adding a reference to assembly `System.ObjectModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' (CS0012)
```

Thing is, I'm already using `System.ComponentModel.INotifyPropertyChanged` in the project and it's working. I'm also targeting .NET 4.5, so not sure why it says `Version=4.0.0.0`, or even if that's referring to the .NET version or not.

My current workaround is to just not use `Bind()` at all, but I'd appreciate any input on this, as it sounds like it would be a very useful feature to have. :)

**Comment by aritchie** [comment]
Unfortunately, I have no idea what may causing this for you.  I know Xamarin.Mac has a ton of issues on VS.  You are best to ask this question of xamarin directly.

**Comment by Dids** [comment]
@aritchie Found the issue. It looks like it's only happening in Visual Studio for Mac, but not in Xamarin Studio. Since everything else (other projects too) works fine in VS for Mac, and I think they're using the same version of Mono now, I never thought to test it in XS. My bad! :)

**Comment by aritchie** [comment]
Thanks for letting me know.  Glad you got your answer
