### ISSUE TITLE
Windows Phone 8 Silverlight does not work

### ISSUE THREAD

**Issue by petero-dk** [aritchie/settings#2]
When using the library from WP8 is throws the error:

Platform plugin not found.  Did you reference the nuget package in your platform project?

I have double checked (via JustDecompile) that it references the library in "wp8" and that library does not have an actual implementation but simple throws that error. It seems like a compile/nuget packaging problem.

**Comment by aritchie** [comment]
The wp8 works for 8/8.1 silverlight.  WPA81 should work on the same windows implementation

**Comment by aritchie** [comment]
wp8 does have broken registration though.  that will be fixed based on your PR.  Thanks

**Comment by petero-dk** [comment]
The Windows Phone 8.0 implementation should also work with WP7 (however building for that is tedious by now). I need it myself, but I don't know if you would be interested in an additional project that could build for that?

**Comment by aritchie** [comment]
Targeting WP7 would be a fair bit of a pain due to the PCL targets.  Did the latest 4.3.2 fix things for you on wp8/81?

**Comment by petero-dk** [comment]
No, 4.3.2 did not fix things - it still does not have two different implementations for WP8.0 and WP8.1 if you look at my pull request I have renamed your current WP project to Acr.Settings.WindowsPhone81 (and retargeted it to Windows Phone 8.1) and added Acr.Settings.WindowsPhone80 with a 8.0 target.

When building the nuget package you need to reference both.

Regarding the WP7, what I meant was that I will anyway create a project for WP7, and build it - if you want I can add that as a pull request additionally?

**Comment by petero-dk** [comment]
There is another problem with the implementation and serialization, let me just investigate and come with a complete working solution. I was a little too quick to send a pull request.

**Comment by petero-dk** [comment]
So the implementation I added a pull request for, does actually work for Windows Phone 8.0, doing simple storage. However complex objects (Dictionaries need to be serialized) - I am adding this to the pull request.

Additionally serializing really complex objects (such as Lists of interfaces) ends up with a Json Serializer exception which I suspect is the same in all (iOS, Android, WP) that uses serialization to store info. For this there are two solutions and I am battling which one I find most appropriate:
1. Keep source at it is now, and let the user set a Default JsonSerializationOption
2. Force TypeNameHandling=Auto before calling JsonConvert.SerializeObject

The arguments for 1. is simple source, and user customization.

The arguments for 2. is this is hidden json so the user should not care how it looks anyway, and the user might use the defaultjsonoptions for something important somewhere else.

**Comment by aritchie** [comment]
There is an implementation for WP8.1.  Another implementation is not necessary.  Acr.Settings.Windows is for WP8.1 and Win8.1.  Acr.Settings.WindowsPhone is meant for WP8-SL.

I'll write up some unit tests for both platforms sometime in the next couple of days and make sure this is dealt with.

**Comment by petero-dk** [comment]
I have not added a new implementation for WP8.1 (WP8.1 SL) just renamed your old one. The difference beeing that if you choose to target WP8.0 SL the current implementation fails. Then you can use mine. However the WP8.0SL does not support roaming profiles. The WP8.1SL solution does allow for roaming profiles.

Does this make any sense at all? Even I am a little confused by what I just wrote.

**Comment by aritchie** [comment]
You shouldn't need another project either.  I get what you're trying to do, I'm just saying it shouldn't be necessary.  I should have unit tests to cover this issue anyhow.  I just need a couple of days.

**Comment by aritchie** [comment]
As for WP7.  I appreciate the offer of a PR, but I'll pass.  It isn't something I want to carry forward especially with WP10 right around the corner.  Also, the PCL bait library is at a profile that is WP8+ (259)

**Comment by aritchie** [comment]
I have been unable to find an issue with 4.3.2. 

For WP8+ silverlight clients - you will get Acr.Settings.WindowsPhone (metadata is tagged in the library)

For WPA81 and Win81 - you will get Acr.Settings.Windows (metadata is tagged in library)

All libraries appear to work properly.

**Comment by petero-dk** [comment]
(Was just away on vacation)

The problem is that what is supported on Windows Phone 8.1 Silverligt is not supported on Windows Phone 8.0 Silverligt (even though it compiles!) - It will fail in runtime.

Windows Phone 8.0 Silverlight ONLY supports:
* IsolatedStorageSettings.ApplicationSettings

Windows Phone 8.1 Silverlight supports both:
* IsolatedStorageSettings.ApplicationSettings (only for backwards compatibility)
and 
* ApplicationData.Current.RoamingSettings (for forwards compatibility)
* ApplicationData.Current.LocalSettings;

You need to 1. either change the implementation of the project Acr.Settings.WindowsPhone to IsolatedStorage or do as I have suggested above add an additional project so you have to implementations for WP8.0 and WP8.1

(Fair enough on the WP7 project)

**Comment by aritchie** [comment]
@petero-dk  thanks for all of your help on this.  

So here's what needs to happen.  
- WP8 support will become WP silverlight support using IsolatedStorageSettings.ApplicationSettings
- Acr.Settings.Windows will be the support for win8 and wpa81 (native - no change here)
- Supporting WP81 silverlight isn't worthwhile since wp8-sl can take care of it.

Unfortunately, windows phone emulators don't work on my machine.  I do have an actual winphone but it is on 8.1.  I will have to find a way to test this before I can release.

**Comment by petero-dk** [comment]
You are welcome, I have though one comment. It seams the Json.net part of you idea is not implemented for the wp8-sl now? Is that correct? 

For really complex objects (objects stored with the interface type, dictionaries etc) the IsolatedStorage cannot cope, and fails. 

I would recommend adding the json implementation from the Acr.Settings.iOS to the wp8-sl


Additionally I have two small requests (one to help me, and one to fix a small error) would you rather have them as pull-requests or issues?

**Comment by aritchie** [comment]
Alright.  This is all sorted out now.... serialization included.  If you have any additional test cases, please let me know.

For your additional requests, please file them as separate issues/requests.  It helps keep a checklist of done/yes/no.

**Comment by petero-dk** [comment]
It looks pretty good now, I have added two pull requests, one to fix the missing Save call in the new Windows Phone implementation - it does not persist settings now.

Additionally I have discovered that if you change the locale of the device you may end up with errors regarding the deserialization of simple values - I have added another pull request to fix that.

**Comment by aritchie** [comment]
I'm not going to change the default serializer settings, but I'll open it up for configuration on the service.
