### ISSUE TITLE
System.ArgumentException: [Acr.Settings] Platform plugin not found.  Did you reference the nuget package in your platform project?

### ISSUE THREAD

**Issue by dagostinelli** [aritchie/settings#21]
Before you write it, I already included the Acr.Settings NuGet package in my PCL, Android and iOS projects.  I'm still getting this exception in MainActivity.cs, OnCreate() when I call `Acr.Settings.Settings.Current.Set<string>("test", "test");`

Just to make sure it's not a really easy problem, I did this:
1) Create new Project in Visual Studio (Xamarin with PCL) (delete the UWP project)
2) Go to NuGet and get Acr.Settings, install it in PCL, Android and iOS projects
3) Open MainActivity.cs
4) Type in `Acr.Settings.Settings.Current.Set<string>("test", "test");`
5) Compile, Run
`<works!>`

It must be something other than forgetting to include the NuGet in the platform assemblies.

**Comment by aritchie** [comment]
I'll need a reproducible test case.  I use this library literally everywhere without issue.

If you want to check what library is being pulled into the compile, use explorer, go into your platform bin, and check the title of the DLL included.

**Comment by dagostinelli** [comment]
This just happened again after doing a mass upgrade of all packages in my project.  

To fix it, I re-targeted the Android project to a different Target Framework, built and deployed. Then changed it back to the one I wanted.  That cleared it up and I wasn't able to reproduce it.

These aren't reproducible instructions, but, since it just happened again, I thought I should document it in case someone else happens across it or my future self happens across it again.

**Comment by aritchie** [comment]
Because I raised the deployment target to android8 intentionally.  It will show this in the nuget package itself.

**Comment by Dokman** [comment]
@aritchie what happens if i use wpf and everytime arise this point?
