### ISSUE TITLE
[8.0 Release] System.ArgumentException: [Acr.Settings] Platform plugin not found. Did you reference the nuget package in your platform project?

### ISSUE THREAD

**Issue by Dokman** [aritchie/settings#25]
So i am having this problem in a wpf project with the newest release version and the repo project referenced too what's happening?

**Comment by aritchie** [comment]
I moved the project to .net standard 2.0  and .net 4.7 to ensure compatibility.

**Comment by Dokman** [comment]
how i can move my project? i am at 4.6.1 to 4.7 my nuget packages aren't compatible... T_T

**Comment by aritchie** [comment]
they should be.  honestly though, that goes beyond the scope of this library.
