### ISSUE TITLE
I dont seem to understand how to use this great plugin,no sample code or FAQ 

### ISSUE THREAD

**Issue by chrisgate** [aritchie/settings#26]
I installed it but dont seem to know how to use it bcoz the readme its not helping.

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [] tvOS
 - [] macOS
 - [] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
The readme has all of the docs you need.  I did notice that I have to change Settings.  to CrossSettings which I'll update today.  Other than that, there are unit tests and the code is open source.  

Please try not to complain about docs in OSS.  I created the library to help others, but it certainly doesn't mean I have to document anything.  I know how to use it.  The code is there.  You should be reviewing it to see if it meets your needs and so you have a thorough understanding of what it does before using it anyhow.

**Comment by chrisgate** [comment]
Thanks @aritchie
