### ISSUE TITLE
Double quotes around strings

### ISSUE THREAD

**Issue by redwards1966** [aritchie/settings#7]
I already a have a settings abstraction that I'm trying to fit your library into and I'm getting a weird error with a string.

My SettingsServices.cs looks like this:

	public class SettingsService
	{
		public static void Set(string key, object value){
			Settings.Local.Set (key, value);
		}

		public static T Get<T>(string key, T @default){
			if (Settings.Local.Contains(key)) {
				return Settings.Local.Get<T> (key);
			}
			return @default;
		}

		public static void Remove(string key) {
			if (Settings.Local.Contains(key)) {
				Settings.Local.Remove (key);
			}
		}
	}

If I call this from my app as such:

    SettingsService.Set ("TEST1", "THIS IS A TEST");

when I grab it back using:

    SettingsService.Get ("TEST1", "MYDEFAULT");

I get back "THIS IS A TEST" with literal double quotes around it. If I change my implementation of Set to Set(string key, string value) then it comes back as expected with no double quotes around it.

Any ideas?

**Comment by aritchie** [comment]
Type inference on your Set(string key, object value);

I use Set<T>(string key, T value) and attempt to figure out the serialization against T.  With that being removed from the equation, it will be shoving the object through the json serializer

**Comment by redwards1966** [comment]
Thanks for the quick reply!

Changed my Set method to:

    		public static void Set<T>(string key, T value){
			Settings.Local.Set (key, value);
		}

and it's working properly for me now.

Particularly like the change notification on this library. Very slick!

Cheers!
