### ISSUE TITLE
Roaming on android doesn't work

### ISSUE THREAD

**Issue by hetadesu** [aritchie/settings#8]
Hi,

I initialized roaming in OnCreate in my main activity but roaming settings doesn't work.

When I close and reopen the app the settings are lost.

Local settings work OK

Thanks,

**Comment by aritchie** [comment]
Are you using the settings in another application?  How are you initializing it?  Is the namespace consistent?

**Comment by hetadesu** [comment]
I use the iOS version too, it works well.

I switched to Local settings for Android

I tested by fetching the SharedPreferences("mynamespace", context) manually but it was empty

I'm really in a hurry I can't dig deeper at the moment sorry :(
