### ISSUE TITLE
ProtectedDataDidBecomeAvailable

### ISSUE THREAD

**Issue by softlion** [aritchie/settings#9]
Hi,
i just found an issue: when the app is running in the background and the device is locked, settings can not be written. It fails with a write access error.

This seems to be related to the ApplicationDelegate.ProtectedDataDidBecomeAvailable callback. I added there NSUserDefaults.ResetStandardUserDefaults(); so settings are reloaded correctly if the app was launched in background while the device is locked (by push notification for example).

But it is not sufficient here. Any idea ?

**Comment by aritchie** [comment]
Is there an exception?

**Comment by softlion** [comment]
Yes on device:

cfprefsd[82] <Error>: CFPreferences: error creating file /private/var/mobile/Containers/Data/Application/00EE6DB5-87E5-410B-B88C-EC55EC450FF1/Library/Preferences/fr.kokoa.gogki.plist.E8uwHYm: 1
